name: Build

on: [push, repository_dispatch, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Visual Studio
        uses: ilammy/msvc-dev-cmd@v1
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"
          architecture: "x64"
      - name: Install Python requirements
        shell: bash
        run: >
          python -OO -m pip install --disable-pip-version-check --upgrade nuitka nuitka zstandard &&
            python -OO -m pip install --disable-pip-version-check -r requirements.txt
      - name: Build executable
        shell: powershell
        run: >
          python -OO -m nuitka --standalone --onefile --python-flag=-OO --assume-yes-for-downloads --static-libpython=auto --windows-disable-console --windows-icon-from-ico=icon.ico --windows-product-name=P3Dephaser --windows-company-name=darktohka --windows-file-version=1.2.0.0 --windows-file-description=P3Dephaser --enable-plugin=pyside6 -o P3Dephaser.exe main.py
      - uses: actions/upload-artifact@v3
        with:
          name: P3Dephaser
          path: P3Dephaser.exe
